### ISSUE TITLE
Rotate logs

### ISSUE THREAD

**Issue by Neozonz** [moopless/stratum-mining-litecoin#10]
Allow logs to rewrite over themselves after reaching max size of X GB/MB specified in config.py

**Comment by TheSerapher** [comment]
Maybe also allow for logs to be rotated by existing services like logrotate. Would require the software to be okay with files being changed while they are open. Could easily be used by admins that k ow logrotate and keeps an archive of logs.

**Comment by moopless** [comment]
That sounds good to me. I'll look into the options and get some log
rotation going. logrotate sounds like a better long term plan so I will see
what I can do there.

**Comment by moopless** [comment]
Support for logrotate and built in log rotation have been added in e07fb64cf09f45c20af48a6012356417009baddc. Make sure to add LOG_ROTATION, LOG_SIZE, and LOG_RETENTION to the config.py as there are no defaults or checks for them.
