### ISSUE TITLE
Announce block solve on IRC

### ISSUE THREAD

**Issue by Neozonz** [moopless/stratum-mining-litecoin#14]
Announce block solve on IRC into certain channel and network

**Comment by moopless** [comment]
Sounds like a great feature to me. Send me a pull request and I will pull it in.

**Comment by Neozonz** [comment]
Will look into coding this later today or this week.

**Comment by Neozonz** [comment]
Sorry I'll definitely look into this this + next week.
Getting time off from work so should be able to get things done :)

**Comment by moopless** [comment]
For this were you looking to have a bot as a part of stratum, or make a call to another bot?

**Comment by Neozonz** [comment]
I was looking to make it apart of stratum, but it would be nicer to add a JSON API,

**Comment by moopless** [comment]
I took a look at it the other day and it should be pretty easy to do. Either we just have a bot in the channel and announce on the block or call an external API. Let me know what you want to do and we can come up with a good solution.

**Comment by ahmedbodi** [comment]
would this be like the bot in the original stratum, or p2pool?

**Comment by Neozonz** [comment]
No longer required as @ahmedbodi & @TheSerapher are developing one

**Comment by TheSerapher** [comment]
That was @WKNiGHT- :)

**Comment by ahmedbodi** [comment]
lol well I was planning on developing my own anyway :p

Sent from my Windows Phone
