### ISSUE TITLE
Difficulty column did not create automatically if it does not exist

### ISSUE THREAD

**Issue by Neozonz** [moopless/stratum-mining-litecoin#15]
I'm not sure if this is a bug, please close if it is.

Had to manually update pool_worker to include difficulty column on a previous db.

**Comment by moopless** [comment]
Not a bug but I can update the SQL files to do an alter. Ill work on this
tonight.

On Jun 13, 2013, at 12:20 PM, Neozonz notifications@github.com wrote:

I'm not sure if this is a bug, please close if it is.

Had to manually update pool_worker to include difficulty column on a
previous db.

—
Reply to this email directly or view it on
GitHubhttps://github.com/moopless/stratum-mining-litecoin/issues/15
.

**Comment by moopless** [comment]
After importing the sql file it should now update the table properly. Please reopen if there are issues.
