### ISSUE TITLE
Check miner hash protocol vs stratum hash protocol

### ISSUE THREAD

**Issue by Neozonz** [moopless/stratum-mining-litecoin#19]
On connect check if miner's encryption protocol is compatible with what stratum is expecting, if not compatible send error.

Example:
CGMiner with SHA connection - > Scrypt Pool = error

Have many users connectng with SHA to Litecoin pools without even knowing they aren't properly connected.

**Comment by TheSerapher** [comment]
Aren't miners just requesting work? I always thought this is a client only setting how work units are dealt with. If the client isn't requesting sha or scrypt specifically I am not sure if that is fixable.

**Comment by moopless** [comment]
If the clients are not specifying scrypt, most times it will default to sha256 and they will try to submit it. We do throw an error when clients are not using scrypt. Every share will be rejected with "Share is above target" (lib / template_registry.py:235) The problem is that stratum can only see if the work is within the mask (diff1 = 0x0000ffff00000000000000000000000000000000000000000000000000000000). So we are unaware of what they are doing with it until they submit it. 

It would be easy to update that exception to say something else. Most pools say something like "unknown work". It is more of a challenge to run a test  on login as it may change the authentication protocol.

**Comment by Neozonz** [comment]
Maybe force share difficulty to lowest level, then submit 10 share and validate against mask as part of authentication process?

**Comment by moopless** [comment]
I am not sure the clients could handle that. I would be able to send some work to them and check it, but the clients don't have the functionality built in to do it in the authentication phase. I could write something up to check their work and raise and exception on bad hashes. I.e check the hash against the solution when the share is submitted and see if I can make it apparent that they are incorrect. Thoughts?

**Comment by Neozonz** [comment]
Post authentication phase is fine.

Now the check work function can we limit it to 1 share at the lowest difficulty, so we don't waste gpu time + time to share.

Functionality would also not be required on reconnects, just on initial connects.

**Comment by moopless** [comment]
Basic feature implementation in f209f66b24e4b94553b5ee69f8481acd49e898be. Can you verify that it works before I merge it in?

There are 2 new settings that need to be added. The first, CHECK_CLIENT_HASH, will enable the feature. POOL_TARGET_INITIAL will set the low share difficulty for the first share.

**Comment by Neozonz** [comment]
[2013-06-19 19:00:25] Started cgminer 3.2.1
 [2013-06-19 19:00:25] Probing for an alive pool
 [2013-06-19 19:00:26] Disabling extra threads due to dynamic mode.
 [2013-06-19 19:00:26] Tune dynamic intensity with --gpu-dyninterval
 [2013-06-19 19:00:26] Network diff set to 633
 [2013-06-19 19:00:27] Thread 1 being disabled
 [2013-06-19 19:00:32] Rejected 524694fd Diff 3/1 GPU 1  (global name 'pool_worker' is
 [2013-06-19 19:00:32] Stratum from pool 0 requested work restart
 [2013-06-19 19:00:32] Rejected fae4b321 Diff 1/1 GPU 0  (global name 'pool_worker' is
 [2013-06-19 19:00:40] Rejected 8a65fb1d Diff 1/1 GPU 1  (global name 'pool_worker' is
 [2013-06-19 19:00:50] Rejected 6c1fb675 Diff 2/1 GPU 1  (global name 'pool_worker' is
 [2013-06-19 19:00:52] Rejected bc904c4a Diff 1/1 GPU 0  (global name 'pool_worker' is

BACKTRACE

2013-06-19 19:01:13,680 ERROR protocol protocol.process_failure # [Failure instance: Traceback: <type 'exceptions.NameError'>: global name 'pool_worker' is not defined
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/protocol.py:185:dataReceived
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/protocol.py:230:lineReceived
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/services.py:13:_handle_event
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/services.py:81:call
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:134:maybeDeferred
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/services.py:78:_run
/home/stratum-mining-litecoin/mining/service.py:104:submit
]
None

**Comment by moopless** [comment]
Typo in the log. Please pull the new commit and try again. (3422eea)

**Comment by moopless** [comment]
@Neozonz Any update on this?

**Comment by Neozonz** [comment]
Sorry I'm currently moving, will do more testing once settled...

**Comment by Neozonz** [comment]
Will verify this today

**Comment by moopless** [comment]
Thanks.

**Comment by moopless** [comment]
Since this would be too much work to merge back in, I am going to delete the branch. New features will be implemented to block users that submit invalids.
