### ISSUE TITLE
PHP-MMCFE-NG - Issues

### ISSUE THREAD

**Issue by Neozonz** [moopless/stratum-mining-litecoin#3]
'difficulty' table required under pool_worker db
field 'worker' requires to be changed to username
VARDIFF causing issues with hash rate calculations

**Comment by moopless** [comment]
New commit adds the difficulty column and changes the worker id to be the username. The difficulty column in the share table is using the worker target difficulty. This can be factored in as part of the hash rate calculations. I can change this to be the share difficulty if desired.

**Comment by TheSerapher** [comment]
Maybe you should add a remote repository folder as a location into your repository. This way we can edit and modify the structure in one repository (mmcfe-ng already has the entire structure in it as required by the UI).

Not sure what the best action would be. Open for ideas.

**Comment by moopless** [comment]
Sounds good to me. How do I add just the sql folder as the remote repository?

I want to use the pushpool standard as much as possible for this project. The only thing I added was a difficulty column in the pool_worker and shares tables. This way we can track the target difficulty at the time the share was submitted as well as hash rate calculations when vardiff comes into play. Ideally it should be the same after that.

**Comment by TheSerapher** [comment]
I shall add that to my repo then.

Not sure how to make remote branches but I am sure it's not hard.

**Comment by moopless** [comment]
Thanks! I'll see if I can get that working.

**Comment by TheSerapher** [comment]
Since mmcfe-ng does not support vardiff nor will anytime soon, should this be put to backlog? Stratum should allow for these columns to be missing if running on mmcfe-ng?

**Comment by moopless** [comment]
Yeah. That makes sense to me. I'll disable updating  the difficulty table when the VARDIFF_ENABLED = False

**Comment by moopless** [comment]
Closing with 2c0b991522074d0e012815f0158f2f3980142544
