### ISSUE TITLE
Those who have over 180mhash, do you get stratum disconnects?

### ISSUE THREAD

**Issue by litecoinmessiah** [moopless/stratum-mining-litecoin#36]
What could be causing this issue?

I tried adding a SSD drive in the end after doing the following:

I was able to support 100+mhash with without disconnects but anything close to 120mhash or more i got disconnects at share diff 31.5

then i doubled it to 63 and managed to get 175 or so mhash without disconnects.

But stratum gets disconnected, i mean miners get interrupted.

Also added 1 backup rpc, just want to get to the root of the issue here

**Comment by moopless** [comment]
Likely database load. Maybe it is flushing too slowly and the shares are queuing up, eventually leading to a large dump and possibly a disconnect.

A few questions below to isolate the issue.

What is the server load like? Do you see it spike at times? Has the database been optimized (https://raw.github.com/major/MySQLTuner-perl/master/mysqltuner.pl)? Do you see anything in the logs at the times of disconnects?

**Comment by moopless** [comment]
@litecoinmessiah Any updated on the questions above?

**Comment by litecoinmessiah** [comment]
http://i.imgur.com/Yuyz7lU.png

**Comment by litecoinmessiah** [comment]
Well i think it might just be the database load, i do have an ssd now which seems to have solved the problem but i still see my larger miners (17mhash or more) report there workers getting disconnects,

I will be testing out the vardiff soon and reporting results :)

**Comment by moopless** [comment]
@litecoinmessiah That is great news. I'll close this out for now.Reopen if you have issues in the future.
