### ISSUE TITLE
Stack trace on new block template

### ISSUE THREAD

**Issue by moopless** [moopless/stratum-mining-litecoin#38]
The following stack trace can be found in the logs. 

```
2013-07-16 22:51:35,602 INFO template_registry # New template for 2d91c570f86aef85d2dd9245539dbce493da935befc419dcc11d2aa502e69103
2013-07-16 22:51:35,612 ERROR template_registry # [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'write'
/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:1126:gotResult
/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:1113:_inlineCallbacks
/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:380:callback
/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:488:_startRunCallbacks
--- <exception caught here> ---
/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:575:_runCallbacks
/home/erundook/dgc/poolfe/stratum/lib/template_registry.py:133:_update_block
/home/erundook/dgc/poolfe/stratum/lib/template_registry.py:103:add_template
/home/erundook/dgc/poolfe/stratum/mining/subscription.py:26:on_template
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/pubsub.py:54:emit
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/pubsub.py:160:emit
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/pubsub.py:66:emit_single
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/protocol.py:102:writeJsonRequest
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/protocol.py:83:transport_write
]
```

It looks like the block update is failing to update one of the clients.

**Comment by svasva** [comment]
this also leads to a ridiculous amount of rejects

**Comment by moopless** [comment]
Makes sense to me. It is failing to update the client of a new block, so they are submitting on the old block, so all of the shares would likely be invalid. I haven't touched this part of the code so I would expect it is seen on other stratum-mining branches. I'll start investigating.

Is this happening across all miners, or just a few? What clients are they using?

**Comment by svasva** [comment]
all miners. this happened suddenly, everything was fine few days ago
-- 
Vitaly A. Sorokin
Sent with Airmail

On 17 июля 2013 г. at 21:53:42, moopless (notifications@github.com) wrote:

Makes sense to me. It is failing to update the client of a new block, so they are submitting on the old block, so all of the shares would likely be invalid. I haven't touched this part of the code so I would expect it is seen on other stratum-mining branches. I'll start investigating.

Is this happening across all miners, or just a few? What clients are they using?

**Comment by svasva** [comment]
oh, looks like this fixes it: https://github.com/slush0/stratum/commit/8ba1b5fd8a802b981f31dace4cf920cfb4a3907c

**Comment by svasva** [comment]
consider bug as upstream & resolved

**Comment by moopless** [comment]
Thanks for tracking this down. Closing as a resolved 3rd party issue.
