### ISSUE TITLE
[Q] Is there any Stratum fork for PoS SHA256 coins?

### ISSUE THREAD

**Issue by nicoschtein** [moopless/stratum-mining-litecoin#52]
As title says, Is there any Stratum fork for PoS SHA256 coins? or at least any `mmcfe-ng` compatible stratum sha256 fork... ?

**Comment by moopless** [comment]
https://github.com/moopless/stratum-mining-litecoin/commit/9074dd7b846de66f25fbb09095ce641862c34a6d is the commit I used to create the PoS branch. It is from a PPCoin branch that can be found here https://github.com/TheSeven/stratum-mining. I am sure there are others out there as well.
