### ISSUE TITLE
Configure litecoind on the fly in config.py

### ISSUE THREAD

**Issue by Neozonz** [moopless/stratum-mining-litecoin#9]
Search for /$USER/.litecoin/.litecoin.conf
IF NOT FOUND  >> search config.py for litecoin.conf configuration file arguments

LITECOIN_DAEMON1_CFG = /home/litecoin/litecoin.conf
LITECOIN_DAEMON2_CFG = /home/litecoin2/litecoin.conf

Parse configuration data from litecoin.conf and use information instead of the following:
LITECOIN_TRUSTED_HOST = 'localhost'
LITECOIN_TRUSTED_PORT = 8332
LITECOIN_TRUSTED_USER = 'user'
LITECOIN_TRUSTED_PASSWORD = 'somepassword'

LITECOIN_TRUSTED_HOST_1 = 'localhost'
LITECOIN_TRUSTED_PORT_1 = 8332
LITECOIN_TRUSTED_USER_1 = 'user'
LITECOIN_TRUSTED_PASSWORD_1 = 'somepassword'

LITECOIN_TRUSTED_HOST_2 = 'localhost'
LITECOIN_TRUSTED_PORT_2 = 8332
LITECOIN_TRUSTED_USER_2 = 'user'
LITECOIN_TRUSTED_PASSWORD_2 = 'somepassword'

If no CENTRAL_WALLET configured run litecoind getnewaddress and place this in config.py.

**Comment by moopless** [comment]
These changes would not really be on the fly, but rather auto populating the configuration at startup. I am more inclined to put some time into on the fly changes as there could be complications with automatically detecting the configuration variables. I just checked commit 8e362c9a400c790e773d3f2844376a53f2d70d5f  to stratum-lite (it will be ported to the JSON API in the master)  where I created a quick script to add a litecoind instance on the fly. It will not be persistent (yet) , but it allows for some level of operation while the program is running.

**Comment by Neozonz** [comment]
ah nice! :+1:

**Comment by moopless** [comment]
Anything else you would like to see on this?

**Comment by Neozonz** [comment]
Would still like to see auto population if possible ;)
If you're feeling up to it feel free to re-open
